testing_mode = true
payment_provider = "stripe" #bmac if using Buy Me A Coffee
stripe_api_key_test = "rk_test_51Nk8sWSGz77fCvT0UvHHHkzHVgp1XDtQjDbMFJMolDSRwjqIls9BPG1Z7qBIHxiNfTKwkwuLZ61fimFCvliywTXB002Fgm270Y" #only needed if using Stripe
stripe_api_key = "sk_live_..." #only needed if using Stripe
stripe_link = "https://buy.stripe.com/..." #only needed if using Stripe
stripe_link_test = "https://buy.stripe.com/test_6oE3ckfNde4WcLu000" #only needed if using Stripe
client_id = "491449016512-9fp398h70ueofoc4mjsfaukoelfaikmu.apps.googleusercontent.com"
client_secret = "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"
redirect_url_test = 'http://localhost:8501/'
redirect_url = "https://my-cool-saas.streamlit.app/"
bmac_api_key = "ey..." #only needed if using buy me a coffee
bmac_link = "https://www.buymeacoffee.com/..." #only needed if using buy me a coffee
